### ISSUE TITLE
Make user nagios managed 

### ISSUE THREAD

**Issue by rweigle** [Icinga/puppet-icinga#41]
It would be useful if the creation of the nagios user ist optional. In our enviroment due to check_by_ssh with forced_commands the user nagios must be managed separately (by the accounts module). This is in conflict with the icinga module. 
A working diff (for Debian):
```
--- a/manifests/init.pp
+++ b/manifests/init.pp
@@ -39,7 +39,6 @@
 #
 class icinga(
   Boolean                              $ca,
-  Boolean                              $manage_user,
   String                               $this_zone,
   Hash[String, Hash]                   $zones,
   Enum['dsa','ecdsa','ed25519','rsa']  $ssh_key_type    = 'rsa',
@@ -135,12 +134,10 @@ class icinga(
             before => User['nagios'],
           }

-          if $manage_user==true {
-            user { 'nagios':
-              ensure => present,
-              shell  => $icinga_shell,
-              before => Class['icinga2'],
-            }
+          user { 'nagios':
+            ensure => present,
+            shell  => $icinga_shell,
+            before => Class['icinga2'],
           }
         } # Debian
```

**Comment by lbetz** [comment]
Sorry for the long wait. Currently I would not specify a pubkey, then no authorized_keys will be generated. The file must then be managed separately itself.
For the future I would plan to remove the pubkey part from this class and provide a separate class, since a scenario for ssh without agent is more likely anyway.
